name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno fmt --check .
      - run: deno lint .
      - run: deno check ./pkgm.ts

  #TODO test on linux! we are currently broken due to rpath issues
  # https://github.com/pkgxdev/pkgm/pull/30#issuecomment-2678957666
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/setup@v3

      - run: |
          if [[ "$(/usr/local/bin/pkgx --version)" != "pkgx 2"* ]]; then
            exit 1
          fi

      - run: ./pkgm.ts i git
      - run: /usr/local/bin/git --version

      - run: ./pkgm.ts i pkgx.sh/brewkit
      - run: /usr/local/bin/bk --help

      # check repeats work
      - run: rm /usr/local/bin/bk
      - run: test ! -f /usr/local/bin/bk
      - run: ./pkgm.ts i pkgx.sh/brewkit
      - run: /usr/local/bin/bk --help

      - run: ./pkgm.ts li gum
      - run: ~/.local/bin/gum --version

      # https://github.com/pkgxdev/pkgm/issues/24
      - run: ./pkgm.ts i curl
      - run: /usr/local/bin/curl -L pkgx.sh

      # TODO pending: https://github.com/pkgxdev/pantry/issues/8487
      # - run: ./pkgm.ts i xpra.org # https://github.com/pkgxdev/pkgm/issues/13
      # - run: ls -la /usr/local/pkgs/xpra.org/v6.2.3/venv/bin
      # - run: xpra --version
